#include "errors.h"


wxString _err_msgs[B1_RES_LASTERRCODE_ALL - B1_RES_FIRSTERRCODE + 1] =
{
	_("invalid token"),
	_("program line too long"),
	_("invalid line number"),
	_("invalid statement"),
	_("invalid argument"),
	_("expression too long"),
	_("missing comma or bracket"),
	_("unbalanced brackets"),
	_("wrong argument count"),
	_("expression evaluation temporary stack overflow"),
	_("unknown syntax error"),
	_("wrong argument type"),
	_("not enough memory"),
	_("invalid memory block descriptor"),
	_("buffer too small"),
	_("string too long"),
	_("too many open brackets"),
	_("unknown identifier"),
	_("wrong subscript count"),
	_("type mismatch"),
	_("subscript out of range"),
	_("identifier already in use"),
	_("integer divide by zero"),
	_("nested IF statement not allowed"),
	_("ELSE without IF"),
	_("line number not found"),
	_("statement stack overflow"),
	_("statement stack underflow"),
	_("can't use the reserved word in this context"),
	_("not a variable"),
	_("environment fatal error"),
	_("unexpected RETURN statement"),
	_("unexpected end of program"),
	_("the end of DATA block reached"),
	_("WEND without WHILE"),
	_("NEXT without FOR"),
	_("FOR without NEXT"),
	_("can't use subscripted variable as FOR loop control variable"),
	_("invalid number"),
	_("numeric overflow"),
	_("too many DEF statements"),
	_("user functions stack overflow"),
	_("end of file"),
	_("use of a reserved keyword as identifer forbidden"),
	_("WHILE without WEND"),
	_("BREAK or CONTINUE statement not within a loop"),
	_("too many breakpoints"),

	_("cannot convert UTF-16 character to UCS-2"),
	_("unknown message queue error"),
	_("input interrupted"),
};
